###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    # postgres:
    #     image: 'postgres:14-alpine'
    #     container_name: "laravel-kafka-postgres"
    #     working_dir: /application
    #     volumes:
    #         - '.:/application'
    #     environment:
    #         - POSTGRES_USER=forge
    #         - POSTGRES_PASSWORD=forge
    #         - POSTGRES_DB=forge
    #     ports:
    #         - '5432:5432'

    webserver:
        image: 'nginx:alpine'
        container_name: "laravel-kafka-webserver"
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'

    php-fpm:
        build: phpdocker/php-fpm
        container_name: "laravel-kafka-php-fpm"
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini'
    
    # zookeeper:
    #     image: "bitnami/zookeeper:latest"
    #     container_name: "laravel-kafka-zookeeper"
    #     ports:
    #         - "2181:2181"
    #     environment:
    #         - ALLOW_ANONYMOUS_LOGIN=yes

    # # See:
    # # https://hub.docker.com/r/bitnami/kafka
    # kafka:
    #     image: bitnami/kafka:2.5.0
    #     container_name: "laravel-kafka-kafka"
    #     ports:
    #         - "9092:9092"
    #     environment:
    #         - KAFKA_BROKER_ID=1
    #         - KAFKA_LISTENERS=PLAINTEXT://:9092
    #         - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://laravel-kafka-kafka:9092
    #         - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    #         - ALLOW_PLAINTEXT_LISTENER=yes
    #     depends_on:
    #         - zookeeper
    
    # kafdrop:
    #     image: obsidiandynamics/kafdrop
    #     container_name: "laravel-kafka-kafdrop"
    #     restart: "no"
    #     ports:
    #     - "9003:9003"
    #     environment:
    #         KAFKA_BROKERCONNECT: "laravel-kafka-kafka:9092"
    #         JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    #         CMD_ARGS: "--server.port=9003"
    #     depends_on:
    #     - "kafka"
